-- Sergio Garcia


DROP DATABASE IF EXISTS SMARTPHONES;

CREATE DATABASE SMARTPHONES DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci;

USE SMARTPHONES;


-- Usuarios registrados	
CREATE TABLE 100_USUARIOS (
	100_idusuario SMALLINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, 
	100_nick VARCHAR( 10 ) UNIQUE NOT NULL,
	100_correo VARCHAR( 30 ) UNIQUE NOT NULL,
	100_contrasena VARCHAR( 20 ) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;


-- Tipos de redes G
CREATE TABLE 200_REDES ( 
	200_idred TINYINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	200_nombre VARCHAR( 10 ) UNIQUE NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;


-- Tipos de sensores
CREATE TABLE 300_SENSORES ( 
	300_idsensor TINYINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	300_nombre VARCHAR( 20 ) UNIQUE NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;


-- Colores de cada modelo
CREATE TABLE 400_COLORES ( 
	400_idcolor TINYINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	400_nombre VARCHAR( 15 ) UNIQUE NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;


-- Tipo de sim
CREATE TABLE 500_SIM ( 
	500_idsim TINYINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	500_nombre VARCHAR( 15 ) UNIQUE NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;


-- Procesadores
CREATE TABLE 600_PROCESADORES (
	600_idprocesador TINYINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	600_nombre VARCHAR( 15 ) UNIQUE NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;


-- Sistemas Operativos
CREATE TABLE 700_SO (
	700_idso TINYINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	700_nombre VARCHAR( 15 ) UNIQUE NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;


-- Paises
CREATE TABLE 800_PAISES (
	800_idpais CHAR( 3 ) PRIMARY KEY,
	800_iso1 CHAR( 2 ) UNIQUE NOT NULL,
	800_iso2 CHAR( 3 ) UNIQUE NOT NULL,
	800_nombre VARCHAR( 30 ) UNIQUE NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;


-- Camaras
CREATE TABLE 900_CAMARAS (
	900_idcamara SMALLINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	900_mp TINYINT UNSIGNED NOT NULL,
	900_focal FLOAT( 2, 1 ) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;


-- Memorias ram
CREATE TABLE 1000_RAM (
	1000_idram TINYINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	1000_memoria TINYINT UNSIGNED NOT NULL,
	1000_mag CHAR( 2 ) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;


-- Memorias almacenamientos
CREATE TABLE 2000_ALMACENAMIENTOS (
	2000_idalmacenamiento TINYINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	2000_memoria TINYINT UNSIGNED NOT NULL,
	2000_mag CHAR( 2 ) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;


-- Marcas
CREATE TABLE 850_MARCAS (
	850_idmarca TINYINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	850_nombre VARCHAR( 10 ) UNIQUE NOT NULL,
	800_idpais CHAR( 3 ) NOT NULL,
	CONSTRAINT FK_850_800_idpais FOREIGN KEY ( 800_idpais ) REFERENCES 800_PAISES ( 800_idpais )
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;


-- Smartphones
CREATE TABLE 852_SMARTPHONES (
	852_idsmartphone SMALLINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	852_familia VARCHAR( 15 ) NOT NULL,
	850_idmarca TINYINT UNSIGNED NOT NULL,
	700_idso TINYINT UNSIGNED NOT NULL,
	CONSTRAINT FK_852_850_idmarca FOREIGN KEY ( 850_idmarca ) REFERENCES 850_MARCAS ( 850_idmarca ),
	CONSTRAINT FK_852_700_idso FOREIGN KEY ( 700_idso ) REFERENCES 700_SO ( 700_idso )
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;


-- Modelos de cada smartphone
CREATE TABLE 855_MODELOS (
	855_idmodelo SMALLINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, 
	855_nombre VARCHAR( 25 ) NOT NULL,
	855_anio YEAR( 4 ) NOT NULL,
	855_alto FLOAT( 4, 1 ) NOT NULL,
	855_ancho FLOAT( 3, 1 ) NOT NULL,
	855_grosor FLOAT( 3, 1 ) NOT NULL,
	855_peso FLOAT( 3, 0 ) NOT NULL,
	855_bateria FLOAT( 4, 0 ) NOT NULL,
	855_multisim BOOLEAN NOT NULL,
	855_sd BOOLEAN NOT NULL,
	855_jack BOOLEAN NOT NULL,
	500_idsim TINYINT UNSIGNED NOT NULL,
	600_idprocesador TINYINT UNSIGNED NOT NULL,
	852_idsmartphone SMALLINT UNSIGNED NOT NULL,
	CONSTRAINT FK_855_500_idsim FOREIGN KEY ( 500_idsim ) REFERENCES 500_SIM ( 500_idsim ),
	CONSTRAINT FK_855_600_idprocesador FOREIGN KEY ( 600_idprocesador ) REFERENCES 600_PROCESADORES ( 600_idprocesador ),
	CONSTRAINT FK_855_852_idsmartphone FOREIGN KEY ( 852_idsmartphone ) REFERENCES 852_SMARTPHONES ( 852_idsmartphone )
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;


-- Comentarios de los usuarios
CREATE TABLE 150_COMENTARIOS (
	150_idcomentario MEDIUMINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	150_comentario TEXT NOT NULL,
	150_fecha DATETIME NOT NULL,
	855_idmodelo SMALLINT UNSIGNED NOT NULL,
	100_idusuario SMALLINT UNSIGNED NOT NULL,
	CONSTRAINT FK_150_855_serie FOREIGN KEY ( 855_idmodelo ) REFERENCES 855_MODELOS ( 855_idmodelo ),
	CONSTRAINT FK_150_100_idusuario FOREIGN KEY ( 100_idusuario ) REFERENCES 100_USUARIOS ( 100_idusuario )
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;


-- Conectividades que tiene cada modelo
CREATE TABLE 255_MODELOS_REDES (
	855_idmodelo SMALLINT UNSIGNED NOT NULL,
	200_idred TINYINT UNSIGNED NOT NULL,
	CONSTRAINT PK_255 PRIMARY KEY ( 855_idmodelo, 200_idred ),
	CONSTRAINT FK_255_855_serie FOREIGN KEY ( 855_idmodelo ) REFERENCES 855_MODELOS ( 855_idmodelo ),
	CONSTRAINT FK_255_200_idred FOREIGN KEY ( 200_idred ) REFERENCES 200_REDES ( 200_idred )
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;


-- Sensores que tiene cada modelo
CREATE TABLE 355_MODELOS_SENSORES (
	855_idmodelo SMALLINT UNSIGNED NOT NULL,
	300_idsensor TINYINT UNSIGNED NOT NULL,
	CONSTRAINT PK_355 PRIMARY KEY ( 855_idmodelo, 300_idsensor ),
	CONSTRAINT FK_355_855_serie FOREIGN KEY ( 855_idmodelo ) REFERENCES 855_MODELOS ( 855_idmodelo ),
	CONSTRAINT FK_355_300_idsensor FOREIGN KEY ( 300_idsensor ) REFERENCES 300_SENSORES ( 300_idsensor )
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;


-- Gama de colores de cada modelo
CREATE TABLE 455_MODELOS_COLORES (
	855_idmodelo SMALLINT UNSIGNED NOT NULL,
	400_idcolor TINYINT UNSIGNED NOT NULL,
	CONSTRAINT PK_455 PRIMARY KEY ( 855_idmodelo, 400_idcolor ),
	CONSTRAINT FK_455_855_serie FOREIGN KEY ( 855_idmodelo ) REFERENCES 855_MODELOS ( 855_idmodelo ),
	CONSTRAINT FK_455_400_idcolor FOREIGN KEY ( 400_idcolor ) REFERENCES 400_COLORES ( 400_idcolor )
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;


-- Imagenes de cada modelo
CREATE TABLE 857_IMAGENES (
	857_idimagen MEDIUMINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	857_ruta VARCHAR( 50 ) UNIQUE NOT NULL,
	855_idmodelo SMALLINT UNSIGNED NOT NULL,
	CONSTRAINT FK_857_855_serie FOREIGN KEY ( 855_idmodelo ) REFERENCES 855_MODELOS ( 855_idmodelo )
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;


-- Camaras que tiene cada modelo
CREATE TABLE 955_MODELOS_CAMARAS (
	855_idmodelo SMALLINT UNSIGNED NOT NULL,
	900_idcamara SMALLINT UNSIGNED NOT NULL,
	955_video CHAR( 15 ),
	955_numero TINYINT UNSIGNED NOT NULL,
	955_tipo BOOLEAN NOT NULL,
	CONSTRAINT PK_955 PRIMARY KEY ( 855_idmodelo, 900_idcamara ),
	CONSTRAINT FK_955_855_serie FOREIGN KEY ( 855_idmodelo ) REFERENCES 855_MODELOS ( 855_idmodelo ),
	CONSTRAINT FK_955_900_idcamara FOREIGN KEY ( 900_idcamara ) REFERENCES 900_CAMARAS ( 900_idcamara )
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;


-- Capacidades de memoria de cada modelo
CREATE TABLE 1555_VARIANTES (
	855_idmodelo SMALLINT UNSIGNED NOT NULL,
	1000_idram TINYINT UNSIGNED NOT NULL,
	2000_idalmacenamiento TINYINT UNSIGNED NOT NULL,
	1555_precio FLOAT( 6, 2 ) NOT NULL,
	CONSTRAINT PK_1555 PRIMARY KEY ( 855_idmodelo, 1000_idram, 2000_idalmacenamiento ),
	CONSTRAINT FK_1555_855_serie FOREIGN KEY ( 855_idmodelo ) REFERENCES 855_MODELOS ( 855_idmodelo ),
	CONSTRAINT FK_1555_1000_idram FOREIGN KEY ( 1000_idram ) REFERENCES 1000_RAM ( 1000_idram ),
	CONSTRAINT FK_1555_2000_idalmacenamiento FOREIGN KEY ( 2000_idalmacenamiento ) REFERENCES 2000_ALMACENAMIENTOS ( 2000_idalmacenamiento )
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;


-- Moviles que tiene cada usuario registrados en su perfil
CREATE TABLE 155_COMPRAS (
	100_idusuario SMALLINT UNSIGNED NOT NULL,
	855_idmodelo SMALLINT UNSIGNED NOT NULL,
	1000_idram TINYINT UNSIGNED NOT NULL,
	2000_idalmacenamiento TINYINT UNSIGNED NOT NULL,
	155_fecha DATE NOT NULL,
	CONSTRAINT PK_155 PRIMARY KEY ( 100_idusuario, 855_idmodelo, 1000_idram, 2000_idalmacenamiento ),
	CONSTRAINT FK_155_100_idusuario FOREIGN KEY ( 100_idusuario ) REFERENCES 100_USUARIOS ( 100_idusuario ),
	CONSTRAINT FK_155 FOREIGN KEY ( 855_idmodelo, 1000_idram, 2000_idalmacenamiento ) REFERENCES 1555_VARIANTES ( 855_idmodelo, 1000_idram, 2000_idalmacenamiento )
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;


-- Comentarios de los usuarios sobre cada modelo
CREATE TABLE 156_VALORACIONES (
	100_idusuario SMALLINT UNSIGNED NOT NULL,
	855_idmodelo SMALLINT UNSIGNED NOT NULL,
	156_valoracion TINYINT UNSIGNED NOT NULL,
	CONSTRAINT PK_156 PRIMARY KEY ( 100_idusuario, 855_idmodelo ),
	CONSTRAINT FK_156 FOREIGN KEY ( 100_idusuario, 855_idmodelo ) REFERENCES 155_COMPRAS ( 100_idusuario, 855_idmodelo )
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;
	
	
	

